'use client';

import Link from 'next/link';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/router';
import { SIGN_IN_HUB_PATH, SIGN_IN_LOGIN_PATH } from 'lib/authEntry';
import { clearUserSession, readUserSession, writeUserSession } from 'lib/userSession';
import styles from '../SignIn/SignIn.module.scss';

const SignUp = () => {
  const router = useRouter();
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setError(null);
    const form = e.currentTarget;
    const email = (form.elements.namedItem('email') as HTMLInputElement)?.value?.trim();
    const password = (form.elements.namedItem('password') as HTMLInputElement)?.value;
    const confirm = (form.elements.namedItem('confirm') as HTMLInputElement)?.value;
    const adminSetupKey = (
      form.elements.namedItem('adminSetupKey') as HTMLInputElement
    )?.value?.trim();

    if (!email || !password) {
      setError('Enter your email and password.');
      return;
    }
    if (password !== confirm) {
      setError('Passwords do not match.');
      return;
    }
    if (password.length < 8) {
      setError('Password must be at least 8 characters.');
      return;
    }

    try {
      const res = await fetch('/api/auth/register', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({
          email,
          password,
          ...(adminSetupKey ? { adminSetupKey } : {}),
        }),
      });

      const j = (await res.json().catch(() => ({}))) as {
        ok?: boolean;
        role?: 'ADMIN' | 'CLIENT';
        email?: string;
        message?: string;
        error?: string;
      };

      if (!res.ok || !j.ok || !j.role || !j.email) {
        clearUserSession();
        if (j.error === 'email_taken') {
          setError('An account with this email already exists. Sign in instead.');
          return;
        }
        if (j.error === 'password_too_short') {
          setError('Password must be at least 8 characters.');
          return;
        }
        if (j.error === 'email_password_required') {
          setError('Enter your email and password.');
          return;
        }
        if (j.error === 'invalid_admin_setup_key') {
          setError('The admin setup code is invalid or expired.');
          return;
        }
        setError(
          j.message ||
            'Could not create your account. Confirm DATABASE_URL and ADMIN_JWT_SECRET in .env.local, then run: npx prisma migrate deploy',
        );
        return;
      }

      writeUserSession({
        role: j.role,
        email: j.email,
        signedInAt: Date.now(),
      });
    } catch {
      clearUserSession();
      setError('Network error while creating your account.');
      return;
    }

    const destination = readUserSession()?.role === 'client' ? '/demo' : '/dashboard';
    void router.replace(destination);
  };

  return (
    <div className={styles.authShell}>
      <div className={styles.page}>
      <span className={styles.eyebrow}>KDInsight</span>
      <h1 className={styles.title} id="sign-up-heading">
        Create account
      </h1>
      <p className={styles.subtitle}>Register as a client to start selecting demo use cases right away.</p>
      <form className={styles.form} onSubmit={handleSubmit} autoComplete="on" noValidate>
        <div className={styles.field}>
          <label className={styles.label} htmlFor="sign-up-email">
            Email
          </label>
          <input
            id="sign-up-email"
            className={styles.input}
            name="email"
            type="email"
            autoComplete="email"
            required
            placeholder="you@yourbusiness.com"
          />
        </div>
        <div className={styles.field}>
          <label className={styles.label} htmlFor="sign-up-password">
            Password
          </label>
          <input
            id="sign-up-password"
            className={styles.input}
            name="password"
            type="password"
            autoComplete="new-password"
            required
            placeholder="At least 8 characters"
            minLength={8}
          />
        </div>
        <div className={styles.field}>
          <label className={styles.label} htmlFor="sign-up-setup-key">
            Admin setup code <span style={{ fontWeight: 400, textTransform: 'none' }}>(optional)</span>
          </label>
          <input
            id="sign-up-setup-key"
            className={styles.input}
            name="adminSetupKey"
            type="text"
            autoComplete="off"
            placeholder="Enter code generated by an existing administrator"
          />
          <p className={styles.hint}>
            Leave blank for a client account. Only valid admin-generated codes can create administrator accounts.
          </p>
        </div>
        <div className={styles.field}>
          <label className={styles.label} htmlFor="sign-up-confirm">
            Confirm password
          </label>
          <input
            id="sign-up-confirm"
            className={styles.input}
            name="confirm"
            type="password"
            autoComplete="new-password"
            required
            placeholder="••••••••"
            minLength={8}
          />
        </div>
        {error ? (
          <p className={styles.error} role="alert">
            {error}
          </p>
        ) : null}
        <div className={styles.actions}>
          <button type="submit" className={`ui-button-2 primary ${styles.submit}`}>
            Create account
          </button>
        </div>
      </form>
      <p className={styles.note}>
        Already have an account?{' '}
        <Link href={SIGN_IN_LOGIN_PATH} className={styles.inlineLink}>
          Sign in
        </Link>
        {' · '}
        <Link href={SIGN_IN_HUB_PATH} className={styles.inlineLink}>
          Account options
        </Link>
      </p>
      <Link href="/" className={styles.back}>
        ← Back to home
      </Link>
      </div>
    </div>
  );
};

export default SignUp;
